# Basic
title: 唐静
subtitle: tangjing's blogs.
description: 2年RN，3年前端。
# creator: <a href="http://onev.cat">@onevcat</a>
creator: jessietang

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
  title: 随笔
  description: Visit blog

# Navigation buttons in the front page.
nav:
  - {
      title: Projects,
      description: My Projects,
      url: "https://github.com/jessietang",
    }
  - { title: 个人简历, description: A button, url: "/2020/09/my/index.html" }

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
  disqus: vno-jekyll
  # duoshuo:

# Social
social:
  weibo: onevcat
  github: onevcat
  twitter: onevcat
  gplus: 107108267983477358170
  mail: onev@onevcat.com

# Google Analytics
ga:
  # id: your_ga_id
  # host: your_host
